[package]
name = "hello-python-ast"
version = "0.1.0"
edition = "2024"
default-run = "hello-python-ast"

[dependencies]
rustpython-ast = { version = "0.4.0", features = ["visitor"] }
rustpython-parser = "0.4.0"
